### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined  

### ISSUE THREAD

**Issue by prosenjit-manna** [Kurtz1993/ionic-minify#9]
Another error

`/Users/username/dev/appname/node_modules/uglify-js/tools/node.js:76
        files.forEach(function(file){
             ^
TypeError: Cannot read property 'forEach' of undefined
    at Object.exports.minify
(/Users/username/dev/appname/node_modules/uglify-js/tools/node.js:76:14)
    at compress
(/Users/username/dev/appname/hooks/after_prepare/ionic-minify.js:63:29)
    at
/Users/username/dev/appname/hooks/after_prepare/ionic-minify.js:119:11
    at FSReqWrap.oncomplete (fs.js:95:15)
Error: Hook failed with error code 1:
/Users/username/dev/appname/hooks/after_prepare/ionic-minify.js
    at
/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:195:23
    at _rejected
(/usr/local/lib/node_modules/cordova/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:823:30
    at Promise.when
(/usr/local/lib/node_modules/cordova/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch
(/usr/local/lib/node_modules/cordova/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush
(/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)`

**Comment by Kurtz1993** [comment]
Let me check that one, seems to be a problem while collectin the filenames.

**Comment by Kurtz1993** [comment]
Could you please give me the details of your environment? OS, node -v

**Comment by prosenjit-manna** [comment]
Prosenjits-Mac-mini:~ prosenjitmanna$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.10.1
BuildVersion:   14B25
Prosenjits-Mac-mini:~ prosenjitmanna$
Prosenjits-Mac-mini:~ prosenjitmanna$ node -v
v0.12.5
Prosenjits-Mac-mini:~ prosenjitmanna$

**Comment by Kurtz1993** [comment]
Mmm... tested this and not getting any error. Got other information that could be useful to address this issue?

**Comment by ammichael** [comment]
I have the same problem.

```
Starting minifying your files...
Minifying JS file: app.js
/Users/michael/dev/paper_finances/node_modules/uglify-js/tools/node.js:57
        files.forEach(function(file, i){
             ^

TypeError: Cannot read property 'forEach' of undefined
    at Object.exports.minify (/Users/michael/dev/paper_finances/node_modules/uglify-js/tools/node.js:57:14)
    at compress (/Users/michael/dev/paper_finances/hooks/after_prepare/ionic-minify.js:63:29)
    at /Users/michael/dev/paper_finances/hooks/after_prepare/ionic-minify.js:119:11
    at FSReqWrap.oncomplete (fs.js:82:15)
Error: Hook failed with error code 1: /Users/michael/dev/paper_finances/hooks/after_prepare/ionic-minify.js
```

**Comment by Kurtz1993** [comment]
Could you please share details of your environment?
Just Node version and OS, please.
I'll take a look to this at night.

---

Luis Rogelio Hernández López
luis.hlopez@outlook.com [luis.hlopez@outlook.com]
[cid:cm_1447015910087_3] [cid:cm_1447015911011_2] [http://mx.linkedin.com/in/kurtz1993] [cid:cm_1447015911683_1] [https://github.com/Kurtz1993]
Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.0.45&pv=5.1.1&source=email_footer_2] On Wed, Nov 11, 2015 at 11:29 am, Michael Amaral < notifications@github.com [notifications@github.com] > wrote:
I have the same problem.

Starting minifying your files...
Minifying JS file: app.js
/Users/michael/dev/paper_finances/node_modules/uglify-js/tools/node.js:57
        files.forEach(function(file, i){
             ^

TypeError: Cannot read property 'forEach' of undefined
    at Object.exports.minify (/Users/michael/dev/paper_finances/node_modules/uglify-js/tools/node.js:57:14)
    at compress (/Users/michael/dev/paper_finances/hooks/after_prepare/ionic-minify.js:63:29)
    at /Users/michael/dev/paper_finances/hooks/after_prepare/ionic-minify.js:119:11
    at FSReqWrap.oncomplete (fs.js:82:15)
Error: Hook failed with error code 1: /Users/michael/dev/paper_finances/hooks/after_prepare/ionic-minify.js

—
Reply to this email directly or view it on GitHub
[https://github.com/Kurtz1993/ionic-minify/issues/9#issuecomment-155854767] .[https://github.com/notifications/beacon/AFKWdp_br0ETDFzbw2S_TBWf2-vLU_XBks5pE3KBgaJpZM4GZsxZ.gif]

**Comment by ehynds** [comment]
+1. Running node 0.12.7

**Comment by ammichael** [comment]
OS X El Capitan, Node 5.0.0

**Comment by Kurtz1993** [comment]
Is everyone using OS X El Capitan?
I've tested ionic-minify on OS X Yosemite and worked fine with the following specs.

OS: OS X Yosemite 10.10.2
Node: 0.12.7
NPM: 2.11.3

**Comment by Kurtz1993** [comment]
Also tested with Node 5.0.0 and still no problems. I will upload an update on ionic-minify@next for you to test. I only removed some unnecessary dependencies and update UglifyJS dependency.
If you could test this and give me your feedback, it'd be awesome.

Thanks.

**Comment by ammichael** [comment]
Well, removed all my npm packages, reinstalled them all with your update, and got the error again. Here:

```
Michaels-iMac:paper_finances michael$ chmod -R 755 hooks
Michaels-iMac:paper_finances michael$ ionic build android --release
Running command: /Users/michael/dev/paper_finances/hooks/after_prepare/010_add_platform_class.js /Users/michael/dev/paper_finances
add to body class: platform-android
Running command: /Users/michael/dev/paper_finances/hooks/after_prepare/ionic-minify.js /Users/michael/dev/paper_finances
Starting minifying your files...
Minifying JS file: app.js
/Users/michael/dev/paper_finances/node_modules/uglify-js/tools/node.js:76
        files.forEach(function(file){
             ^

TypeError: Cannot read property 'forEach' of undefined
    at Object.exports.minify (/Users/michael/dev/paper_finances/node_modules/uglify-js/tools/node.js:76:14)
    at compress (/Users/michael/dev/paper_finances/hooks/after_prepare/ionic-minify.js:63:29)
    at /Users/michael/dev/paper_finances/hooks/after_prepare/ionic-minify.js:119:11
    at FSReqWrap.oncomplete (fs.js:82:15)
Error: Hook failed with error code 1: /Users/michael/dev/paper_finances/hooks/after_prepare/ionic-minify.js

```

**Comment by Kurtz1993** [comment]
@ammichael can you show me the contents of your minify-conf.json file, please?

**Comment by ammichael** [comment]
Yeap. Here:

```
{
    "foldersToProcess": [
        "js",
        "css",
        "lib",
        "img"
    ],
    "jpgOptions":{
      "quality": 50
    },
    "jsOptions": {
        "compress": {
            "drop_console": true
        },
        "fromString": true
    },
    "cssOptions": {
        "keepSpecialComments": 0
    },
    "alwaysRun": false
}

```

**Comment by Kurtz1993** [comment]
I will try to refactor the way the files are being minified. I'm not getting what's causing the error yet :confused: 
Does a previous version of ionic-minify work for you?

**Comment by ammichael** [comment]
Actually, this was my first time trying to use it. I want to release my app securely, but cant minify ;/

**Comment by ehynds** [comment]
fwiw I am on El Capitan.

**Comment by ammichael** [comment]
Btw, this may be useful. If I remove JS folder in minify-conf.json, it gives the same error but in another point. It does minify a lot of JS files.

Sorry, it's a big log, but since I dont know what could be useful for you, I will include all of it. Here it is:

```
Running command: /Users/michael/dev/paper_finances/hooks/after_prepare/ionic-minify.js /Users/michael/dev/paper_finances
Starting minifying your files...
Minifying CSS file: animate.css
Minifying CSS file: style.css
 file found, not minifying...
Compressing PNG image: Finances-Logo.png
Compressing JPG image: background.jpg
 file found, not minifying...
Minifying JS file: angular-ios9-uiwebview.patch.js
.json file found, not minifying...
.md file found, not minifying...
Minifying JS file: angular-animate.js
.min.js file found, not minifying...
.min.map file found, not minifying...
.json file found, not minifying...
.json file found, not minifying...
.json file found, not minifying...
 file found, not minifying...
.md file found, not minifying...
Minifying JS file: angular-input-masks-debug.js
.min.js file found, not minifying...
Minifying JS file: angular-input-masks-dependencies.js
.min.js file found, not minifying...
Minifying JS file: angular-input-masks-standalone.js
.min.js file found, not minifying...
Minifying JS file: angular-input-masks.br.js
.min.js file found, not minifying...
Minifying JS file: angular-input-masks.js
.min.js file found, not minifying...
Minifying JS file: angular-input-masks.us.js
.min.js file found, not minifying...
.json file found, not minifying...
.json file found, not minifying...
.md file found, not minifying...
Minifying CSS file: angular-csp.css
Minifying JS file: angular-locale_pt-br.js
Minifying JS file: angular.js
.min.js file found, not minifying...
.min.gzip file found, not minifying...
.min.map file found, not minifying...
.json file found, not minifying...
Minifying JS file: index.js
.json file found, not minifying...
 file found, not minifying...
.json file found, not minifying...
.md file found, not minifying...
.md file found, not minifying...
 file found, not minifying...
.md file found, not minifying...
.json file found, not minifying...
.json file found, not minifying...
.md file found, not minifying...
Minifying JS file: angular-sanitize.js
.min.js file found, not minifying...
.min.map file found, not minifying...
.json file found, not minifying...
.json file found, not minifying...
 file found, not minifying...
.json file found, not minifying...
 file found, not minifying...
.md file found, not minifying...
.json file found, not minifying...
Minifying JS file: gulpfile.js
 file found, not minifying...
.json file found, not minifying...
 file found, not minifying...
.yml file found, not minifying...
 file found, not minifying...
 file found, not minifying...
.md file found, not minifying...
Minifying JS file: bowser.js
.min.js file found, not minifying...
.json file found, not minifying...
.json file found, not minifying...
 file found, not minifying...
.json file found, not minifying...
 file found, not minifying...
.md file found, not minifying...
.json file found, not minifying...
Minifying JS file: index.js
.json file found, not minifying...
.md file found, not minifying...
.json file found, not minifying...
Minifying JS file: firebase-debug.js
Minifying JS file: firebase.js
 file found, not minifying...
.json file found, not minifying...
.txt file found, not minifying...
.json file found, not minifying...
 file found, not minifying...
.json file found, not minifying...
 file found, not minifying...
.md file found, not minifying...
.md file found, not minifying...
 file found, not minifying...
.json file found, not minifying...
Minifying JS file: package.js
 file found, not minifying...
 file found, not minifying...
.json file found, not minifying...
.md file found, not minifying...
 file found, not minifying...
.md file found, not minifying...
.json file found, not minifying...
.json file found, not minifying...
 file found, not minifying...
.json file found, not minifying...
 file found, not minifying...
.md file found, not minifying...
.json file found, not minifying...
Minifying JS file: gulpfile.js
Minifying JS file: common.js
Minifying JS file: resolve.js
Minifying JS file: state.js
Minifying JS file: stateDirectives.js
Minifying JS file: stateFilters.js
Minifying JS file: templateFactory.js
Minifying JS file: urlMatcherFactory.js
Minifying JS file: urlRouter.js
Minifying JS file: view.js
Minifying JS file: viewDirective.js
Minifying JS file: viewScroll.js
.ts file found, not minifying...
Minifying JS file: angular-ui-router.js
.min.js file found, not minifying...
Finished compressing PNG image:  Finances-Logo.png
Minifying JS file: br-validations.js
Minifying JS file: build.js
.min.js file found, not minifying...
Minifying JS file: bowser.js
Minifying JS file: copyright.js
Minifying JS file: useragents.js
Minifying JS file: test.js
Minifying JS file: angularfire.js
.min.js file found, not minifying...
Minifying JS file: jquery.js
.min.js file found, not minifying...
.min.map file found, not minifying...
 file found, not minifying...
Minifying JS file: ajax.js
Minifying JS file: attributes.js
Minifying JS file: callbacks.js
Minifying JS file: core.js
Minifying JS file: css.js
Minifying JS file: data.js
Minifying JS file: deferred.js
Minifying JS file: deprecated.js
Minifying JS file: dimensions.js
Minifying JS file: effects.js
Minifying JS file: event.js
Minifying JS file: intro.js
/Users/michael/dev/paper_finances/node_modules/uglify-js/tools/node.js:76
        files.forEach(function(file){
             ^

TypeError: Cannot read property 'forEach' of undefined
    at Object.exports.minify (/Users/michael/dev/paper_finances/node_modules/uglify-js/tools/node.js:76:14)
    at compress (/Users/michael/dev/paper_finances/hooks/after_prepare/ionic-minify.js:63:29)
    at /Users/michael/dev/paper_finances/hooks/after_prepare/ionic-minify.js:119:11
    at FSReqWrap.oncomplete (fs.js:82:15)
Error: Hook failed with error code 1: /Users/michael/dev/paper_finances/hooks/after_prepare/ionic-minify.js
```

**Comment by Kurtz1993** [comment]
Could you please remove lib folder from minify.conf.json and put the js folder
back again and share me your log?
Maybe it has some problems with certain parts of the code or libs.

---

Luis Rogelio Hernández López
luis.hlopez@outlook.com [luis.hlopez@outlook.com]
[cid:cm_1447015910087_3] [cid:cm_1447015911011_2] [http://mx.linkedin.com/in/kurtz1993] [cid:cm_1447015911683_1] [https://github.com/Kurtz1993]
Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.0.55&pv=5.1.1&source=email_footer_2] On Wed, Nov 18, 2015 at 2:52 pm, Michael Amaral < notifications@github.com [notifications@github.com] > wrote:
Btw, this may be useful. If I remove JS folder in minify-conf.json, it gives the
same error but in another point. It does minify a lot of JS files.

Sorry, it's a big log, but since I dont know what could be useful for you, I
will include all of it. Here it is:

Running command: /Users/michael/dev/paper_finances/hooks/after_prepare/ionic-minify.js /Users/michael/dev/paper_finances
Starting minifying your files...
Minifying CSS file: animate.css
Minifying CSS file: style.css
 file found, not minifying...
Compressing PNG image: Finances-Logo.png
Compressing JPG image: background.jpg
 file found, not minifying...
Minifying JS file: angular-ios9-uiwebview.patch.js
.json file found, not minifying...
.md file found, not minifying...
Minifying JS file: angular-animate.js
.min.js file found, not minifying...
.min.map file found, not minifying...
.json file found, not minifying...
.json file found, not minifying...
.json file found, not minifying...
 file found, not minifying...
.md file found, not minifying...
Minifying JS file: angular-input-masks-debug.js
.min.js file found, not minifying...
Minifying JS file: angular-input-masks-dependencies.js
.min.js file found, not minifying...
Minifying JS file: angular-input-masks-standalone.js
.min.js file found, not minifying...
Minifying JS file: angular-input-masks.br.js
.min.js file found, not minifying...
Minifying JS file: angular-input-masks.js
.min.js file found, not minifying...
Minifying JS file: angular-input-masks.us.js
.min.js file found, not minifying...
.json file found, not minifying...
.json file found, not minifying...
.md file found, not minifying...
Minifying CSS file: angular-csp.css
Minifying JS file: angular-locale_pt-br.js
Minifying JS file: angular.js
.min.js file found, not minifying...
.min.gzip file found, not minifying...
.min.map file found, not minifying...
.json file found, not minifying...
Minifying JS file: index.js
.json file found, not minifying...
 file found, not minifying...
.json file found, not minifying...
.md file found, not minifying...
.md file found, not minifying...
 file found, not minifying...
.md file found, not minifying...
.json file found, not minifying...
.json file found, not minifying...
.md file found, not minifying...
Minifying JS file: angular-sanitize.js
.min.js file found, not minifying...
.min.map file found, not minifying...
.json file found, not minifying...
.json file found, not minifying...
 file found, not minifying...
.json file found, not minifying...
 file found, not minifying...
.md file found, not minifying...
.json file found, not minifying...
Minifying JS file: gulpfile.js
 file found, not minifying...
.json file found, not minifying...
 file found, not minifying...
.yml file found, not minifying...
 file found, not minifying...
 file found, not minifying...
.md file found, not minifying...
Minifying JS file: bowser.js
.min.js file found, not minifying...
.json file found, not minifying...
.json file found, not minifying...
 file found, not minifying...
.json file found, not minifying...
 file found, not minifying...
.md file found, not minifying...
.json file found, not minifying...
Minifying JS file: index.js
.json file found, not minifying...
.md file found, not minifying...
.json file found, not minifying...
Minifying JS file: firebase-debug.js
Minifying JS file: firebase.js
 file found, not minifying...
.json file found, not minifying...
.txt file found, not minifying...
.json file found, not minifying...
 file found, not minifying...
.json file found, not minifying...
 file found, not minifying...
.md file found, not minifying...
.md file found, not minifying...
 file found, not minifying...
.json file found, not minifying...
Minifying JS file: package.js
 file found, not minifying...
 file found, not minifying...
.json file found, not minifying...
.md file found, not minifying...
 file found, not minifying...
.md file found, not minifying...
.json file found, not minifying...
.json file found, not minifying...
 file found, not minifying...
.json file found, not minifying...
 file found, not minifying...
.md file found, not minifying...
.json file found, not minifying...
Minifying JS file: gulpfile.js
Minifying JS file: common.js
Minifying JS file: resolve.js
Minifying JS file: state.js
Minifying JS file: stateDirectives.js
Minifying JS file: stateFilters.js
Minifying JS file: templateFactory.js
Minifying JS file: urlMatcherFactory.js
Minifying JS file: urlRouter.js
Minifying JS file: view.js
Minifying JS file: viewDirective.js
Minifying JS file: viewScroll.js
.ts file found, not minifying...
Minifying JS file: angular-ui-router.js
.min.js file found, not minifying...
Finished compressing PNG image:  Finances-Logo.png
Minifying JS file: br-validations.js
Minifying JS file: build.js
.min.js file found, not minifying...
Minifying JS file: bowser.js
Minifying JS file: copyright.js
Minifying JS file: useragents.js
Minifying JS file: test.js
Minifying JS file: angularfire.js
.min.js file found, not minifying...
Minifying JS file: jquery.js
.min.js file found, not minifying...
.min.map file found, not minifying...
 file found, not minifying...
Minifying JS file: ajax.js
Minifying JS file: attributes.js
Minifying JS file: callbacks.js
Minifying JS file: core.js
Minifying JS file: css.js
Minifying JS file: data.js
Minifying JS file: deferred.js
Minifying JS file: deprecated.js
Minifying JS file: dimensions.js
Minifying JS file: effects.js
Minifying JS file: event.js
Minifying JS file: intro.js
/Users/michael/dev/paper_finances/node_modules/uglify-js/tools/node.js:76
        files.forEach(function(file){
             ^

TypeError: Cannot read property 'forEach' of undefined
    at Object.exports.minify (/Users/michael/dev/paper_finances/node_modules/uglify-js/tools/node.js:76:14)
    at compress (/Users/michael/dev/paper_finances/hooks/after_prepare/ionic-minify.js:63:29)
    at /Users/michael/dev/paper_finances/hooks/after_prepare/ionic-minify.js:119:11
    at FSReqWrap.oncomplete (fs.js:82:15)
Error: Hook failed with error code 1: /Users/michael/dev/paper_finances/hooks/after_prepare/ionic-minify.js

—
Reply to this email directly or view it on GitHub
[https://github.com/Kurtz1993/ionic-minify/issues/9#issuecomment-157860010] .[https://github.com/notifications/beacon/AFKWdry3efILgWJf63i2cs7q3JMCazqkks5pHNyFgaJpZM4GZsxZ.gif]

**Comment by Kurtz1993** [comment]
I pushed another update to the ionic-minify@next to deal with those errors.

The hook won't touch those files that got errors while trying to minify/compress and show you in console which ones failed.
I'm making this change because the only way I found to reproduce the error was trying to minify an invalid javascript/css file.
